name: quay.io to docker.io

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: login dockerhub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: pull quay.io
      run: docker pull quay.io/openshift/okd-content:4.5.0-0.okd-2020-07-29-070316-machine-config-operator
    - name: push docker.io
      run: |
        docker tag quay.io/openshift/okd-content:4.5.0-0.okd-2020-07-29-070316-machine-config-operator shinhwagk/quayio_openshift_okd-content:4.5.0-0.okd-2020-07-29-070316-machine-config-operator
        docker push shinhwagk/quayio_openshift_okd-content:4.5.0-0.okd-2020-07-29-070316-machine-config-operator