name: quay.io to docker.io

on:
  push:
    branches: [ master ]

jobs:
  transport:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: login dockerhub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - run: /bin/bash -x transport-quayio.sh
